# Generated by Django 3.2.18 on 2023-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alt_tag', models.CharField(max_length=300)),
                ('highlights', models.CharField(max_length=150, null=True)),
                ('bg_image', models.ImageField(upload_to='midea/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price_latest', models.PositiveIntegerField(default=0)),
                ('product_price_previous', models.PositiveIntegerField(default=0)),
                ('product_quantities', models.PositiveSmallIntegerField(default=0)),
                ('product_size', models.CharField(default=None, max_length=50)),
                ('product_type', models.CharField(choices=[('N', None), ('FW', 'FootWear'), ('WC', "Women's Clothing"), ('S', 'Shoes')], default='N', max_length=10)),
                ('product_for', models.CharField(choices=[('N', None), ('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], default='N', max_length=15)),
                ('product_rating', models.CharField(max_length=10, null=True)),
                ('product_status', models.BooleanField(default=True)),
                ('product_desc', models.TextField()),
                ('product_alt', models.CharField(default='Default ALT Tag', max_length=300, null=True)),
                ('product_meta_desc', models.CharField(default='Meta Decs', max_length=200, null=True)),
                ('images', models.FileField(upload_to='midea/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_for_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Product Name', max_length=300)),
                ('product_original_price', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('product_quantities', models.PositiveSmallIntegerField(default=0)),
                ('product_size', models.CharField(default=None, max_length=50)),
                ('product_type', models.CharField(choices=[('N', None), ('FW', 'FootWear'), ('WC', "Women's Clothing"), ('S', 'Shoes')], default='N', max_length=10)),
                ('product_for', models.CharField(choices=[('N', None), ('M', 'Men'), ('W', 'Women'), ('K', 'Kids')], default='N', max_length=15)),
                ('product_rating', models.CharField(max_length=10, null=True)),
                ('product_status', models.BooleanField(default=True)),
                ('product_desc', models.TextField()),
                ('product_alt', models.CharField(default='Default ALT Tag', max_length=300, null=True)),
                ('product_meta_desc', models.CharField(default='Meta Decs', max_length=200, null=True)),
                ('images', models.FileField(upload_to='midea/images/')),
            ],
        ),
    ]
