# Generated by Django 3.2.18 on 2023-04-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Details',
            new_name='Product_Detail',
        ),
    ]
