# Generated by Django 3.2.18 on 2023-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_rename_product_details_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=200)),
                ('cust_contact', models.PositiveIntegerField()),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_message_subject', models.CharField(max_length=200)),
                ('cust_message', models.TextField(max_length=1000)),
                ('cust_rating', models.PositiveIntegerField(choices=[('N', None), ('W', 'Worst'), ('B', 'Bad'), ('O', 'OK'), ('G', 'Good'), ('E', 'Excellent')], default='N')),
                ('action_taken', models.BooleanField(default=False)),
            ],
        ),
    ]
