# Generated by Django 3.2.18 on 2023-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_contact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_US',
            new_name='Contact_US_Data',
        ),
    ]
