# Generated by Django 3.2.18 on 2023-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_rename_contact_us_data_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='cust_contact',
            field=models.CharField(max_length=30),
        ),
    ]
