# Generated by Django 3.2.18 on 2023-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_alter_contact_us_cust_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='cust_rating',
            field=models.CharField(choices=[('N', None), ('W', 'Worst'), ('B', 'Bad'), ('O', 'OK'), ('G', 'Good'), ('E', 'Excellent')], default='N', max_length=30),
        ),
    ]
