# Generated by Django 3.2.18 on 2023-04-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_alter_contact_us_cust_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='cust_location',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
