# Generated by Django 3.2.18 on 2023-04-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0008_contact_us_cust_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='cust_rating',
        ),
    ]
