# Generated by Django 3.2.18 on 2023-04-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0010_product_for_sale_product_mini_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_US',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title Here', max_length=200)),
            ],
        ),
    ]
