# Generated by Django 3.2.18 on 2023-04-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0012_auto_20230405_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='about_desc',
            field=models.CharField(default='About Description', max_length=300),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_meta_data',
            field=models.CharField(default='Meta Description for About US', max_length=600),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic',
            field=models.ImageField(null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='quote_body',
            field=models.CharField(default='Quote', max_length=300, null=True),
        ),
    ]
