# Generated by Django 3.2.18 on 2023-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0013_auto_20230405_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='about_pic',
            field=models.ImageField(default=None, null=True, upload_to='midea/images/'),
        ),
    ]
