# Generated by Django 3.2.18 on 2023-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0014_alter_about_us_about_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Out_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Member Name', max_length=300)),
                ('email', models.EmailField(default='email ID', max_length=300)),
                ('contact', models.CharField(default='Contact No', max_length=50)),
                ('optional_contact', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(default='Put Address Here')),
                ('designation', models.CharField(default='Put Designation Here', max_length=200)),
                ('about_designation', models.TextField(blank=True)),
                ('profile_ID', models.ImageField(upload_to='midea/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='about_us',
            name='about_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
    ]
