# Generated by Django 3.2.18 on 2023-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0015_auto_20230405_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_team',
            name='address',
            field=models.TextField(blank=True, default='Put Address Here'),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='contact',
            field=models.CharField(blank=True, default='Contact No', max_length=50),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='designation',
            field=models.CharField(blank=True, default='Put Designation Here', max_length=200),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='email',
            field=models.EmailField(blank=True, default='email ID', max_length=300),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='name',
            field=models.CharField(blank=True, default='Member Name', max_length=300),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='optional_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
