# Generated by Django 3.2.18 on 2023-04-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0016_auto_20230405_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='about_pic',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
    ]
