# Generated by Django 3.2.18 on 2023-04-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0017_alter_about_us_about_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic',
            new_name='about_pic_1',
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
    ]
