# Generated by Django 3.2.18 on 2023-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0023_alter_out_team_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='about_pic_6',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_7',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_8',
            field=models.FileField(blank=True, default=None, null=True, upload_to='midea/images/'),
        ),
    ]
