# Generated by Django 3.2.18 on 2023-04-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0024_auto_20230405_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='about_pic_1_atl',
            field=models.CharField(blank=True, default='Add ALT Tag fro this Picture', max_length=250),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_2_atl',
            field=models.CharField(blank=True, default='Add ALT Tag fro this Picture', max_length=250),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_3_atl',
            field=models.CharField(blank=True, default='Add ALT Tag fro this Picture', max_length=250),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_4_atl',
            field=models.CharField(blank=True, default='Add ALT Tag fro this Picture', max_length=250),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_5_atl',
            field=models.CharField(blank=True, default='Add ALT Tag fro this Picture', max_length=250),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_6_atl',
            field=models.CharField(blank=True, default='Add ALT Tag fro this Picture', max_length=250),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_7_atl',
            field=models.CharField(blank=True, default='Add ALT Tag fro this Picture', max_length=250),
        ),
        migrations.AddField(
            model_name='about_us',
            name='about_pic_8_atl',
            field=models.CharField(blank=True, default='Add ALT Tag fro this Picture', max_length=250),
        ),
    ]
