# Generated by Django 3.2.18 on 2023-04-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0025_auto_20230405_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic_1_atl',
            new_name='about_pic_1_atl_TAG',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic_2_atl',
            new_name='about_pic_2_atl_TAG',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic_3_atl',
            new_name='about_pic_3_atl_TAG',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic_4_atl',
            new_name='about_pic_4_atl_TAG',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic_5_atl',
            new_name='about_pic_5_atl_TAG',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic_6_atl',
            new_name='about_pic_6_atl_TAG',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic_7_atl',
            new_name='about_pic_7_atl_TAG',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='about_pic_8_atl',
            new_name='about_pic_8_atl_TAG',
        ),
    ]
