# Generated by Django 3.2.18 on 2023-04-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0026_auto_20230405_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_team',
            name='Discord_profile_Link',
            field=models.CharField(blank=True, default='Facebook Link Here', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='out_team',
            name='Instagram_profile_Link',
            field=models.CharField(blank=True, default='Facebook Link Here', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='out_team',
            name='RedIT_profile_Link',
            field=models.CharField(blank=True, default='Facebook Link Here', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='out_team',
            name='Youtube_Channel_Link',
            field=models.CharField(blank=True, default='Facebook Link Here', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='out_team',
            name='facebook_profile_Link',
            field=models.CharField(blank=True, default='Facebook Link Here', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='out_team',
            name='linkedin_profile_Link',
            field=models.CharField(blank=True, default='Facebook Link Here', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='out_team',
            name='profile_alt_TAG',
            field=models.CharField(blank=True, default='Profile ALT Here', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='out_team',
            name='twitter_profile_Link',
            field=models.CharField(blank=True, default='Facebook Link Here', max_length=400, null=True),
        ),
    ]
