# Generated by Django 3.2.18 on 2023-04-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0029_alter_out_team_redit_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='out_team',
            name='Discord_profile_Link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='Instagram_profile_Link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='Youtube_Channel_Link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='facebook_profile_Link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='linkedin_profile_Link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='out_team',
            name='twitter_profile_Link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
