# Generated by Django 3.2.18 on 2023-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0030_auto_20230405_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_team',
            name='personal_site',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
