# Generated by Django 3.2.18 on 2023-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0031_out_team_personal_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='sub_body_3',
            field=models.TextField(default='Sub Body 3'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='sub_heading_3',
            field=models.CharField(default='Sub Heading 3', max_length=300),
        ),
    ]
