# Generated by Django 3.2.18 on 2023-04-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0032_auto_20230405_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=500)),
                ('location', models.CharField(default='City / State', max_length=500)),
                ('testimonial', models.TextField()),
            ],
        ),
    ]
