# Generated by Django 3.2.18 on 2023-04-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0033_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
    ]
