# Generated by Django 3.2.18 on 2023-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0035_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_2',
            field=models.TextField(default='Sub Body 1'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_3',
            field=models.TextField(default='Sub Body 1'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_4',
            field=models.TextField(default='Sub Body 1'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_5',
            field=models.TextField(default='Sub Body 1'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_6',
            field=models.TextField(default='Sub Body 1'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_7',
            field=models.TextField(default='Sub Body 1'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_8',
            field=models.TextField(default='Sub Body 1'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_2',
            field=models.CharField(default='Sub Heading 1', max_length=500),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_3',
            field=models.CharField(default='Sub Heading 1', max_length=500),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_4',
            field=models.CharField(default='Sub Heading 1', max_length=500),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_5',
            field=models.CharField(default='Sub Heading 1', max_length=500),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_6',
            field=models.CharField(default='Sub Heading 1', max_length=500),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_7',
            field=models.CharField(default='Sub Heading 1', max_length=500),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_8',
            field=models.CharField(default='Sub Heading 1', max_length=500),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_2',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_3',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_4',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_5',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_6',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_7',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_8',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_2',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_3',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_4',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_5',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_6',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_7',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_8',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 1', max_length=500, null=True),
        ),
    ]
