# Generated by Django 3.2.18 on 2023-04-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0036_auto_20230406_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='blog_title_image',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
    ]
