# Generated by Django 3.2.18 on 2023-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0037_blog_content_blog_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='blog_meta_data',
            field=models.CharField(default='Blog Meta Data Here', max_length=500),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='blog_title_image_ALT_TAG',
            field=models.CharField(blank=True, default='Add Image ALT TAG Here', max_length=400, null=True),
        ),
    ]
