# Generated by Django 3.2.18 on 2023-04-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0038_auto_20230406_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_2',
            field=models.TextField(default='Sub Body 2'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_3',
            field=models.TextField(default='Sub Body 3'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_4',
            field=models.TextField(default='Sub Body 4'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_5',
            field=models.TextField(default='Sub Body 5'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_6',
            field=models.TextField(default='Sub Body 6'),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_7',
            field=models.TextField(blank=True, default='Sub Body 7', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_8',
            field=models.TextField(blank=True, default='Sub Body 8', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_2',
            field=models.CharField(default='Sub Heading 2', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_3',
            field=models.CharField(default='Sub Heading 3', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_4',
            field=models.CharField(default='Sub Heading 4', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_5',
            field=models.CharField(default='Sub Heading 5', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_6',
            field=models.CharField(default='Sub Heading 6', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_7',
            field=models.CharField(blank=True, default='Sub Heading 7', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_8',
            field=models.CharField(blank=True, default='Sub Heading 8', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_2',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 2', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_3',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 3', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_4',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 4', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_5',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 5', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_6',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 6', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_7',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 7', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_8',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 8', max_length=500, null=True),
        ),
    ]
