# Generated by Django 4.2 on 2023-04-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0040_blog_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_page',
            name='blog_image',
            field=models.FileField(blank=True, upload_to='midea/images/'),
        ),
    ]
