# Generated by Django 4.2 on 2023-04-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0041_alter_blog_page_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_page',
            name='blog_image',
            field=models.FileField(upload_to='midea/images/'),
        ),
    ]
