# Generated by Django 4.2 on 2023-04-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0042_alter_blog_page_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Content',
        ),
    ]
