# Generated by Django 4.2 on 2023-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0043_delete_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='Blog Title Here', max_length=300)),
                ('blog_summary', models.CharField(default='Blog Summary in few Words', max_length=450)),
                ('blog_meta_data', models.CharField(default='Blog Meta Data Here', max_length=500)),
                ('blog_title_image', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('blog_title_image_ALT_TAG', models.CharField(blank=True, default='Add Image ALT TAG Here', max_length=400, null=True)),
                ('blog_heading_1', models.CharField(default='Blog Heading 1', max_length=200)),
                ('blog_intro', models.TextField(default='Blog Intro')),
                ('blog_date_posted', models.DateTimeField(auto_now_add=True)),
                ('sub_heading_1', models.CharField(default='Sub Heading 1', max_length=500)),
                ('sub_body_1', models.TextField(default='Sub Body 1')),
                ('sub_image_1', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('sub_image_ALT_TAG_1', models.CharField(blank=True, default='Sub Image Default ALT TAG 1', max_length=500, null=True)),
                ('sub_heading_2', models.CharField(default='Sub Heading 2', max_length=500)),
                ('sub_body_2', models.TextField(default='Sub Body 2')),
                ('sub_image_2', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('sub_image_ALT_TAG_2', models.CharField(blank=True, default='Sub Image Default ALT TAG 2', max_length=500, null=True)),
                ('sub_heading_3', models.CharField(default='Sub Heading 3', max_length=500)),
                ('sub_body_3', models.TextField(default='Sub Body 3')),
                ('sub_image_3', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('sub_image_ALT_TAG_3', models.CharField(blank=True, default='Sub Image Default ALT TAG 3', max_length=500, null=True)),
                ('sub_heading_4', models.CharField(default='Sub Heading 4', max_length=500)),
                ('sub_body_4', models.TextField(default='Sub Body 4')),
                ('sub_image_4', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('sub_image_ALT_TAG_4', models.CharField(blank=True, default='Sub Image Default ALT TAG 4', max_length=500, null=True)),
                ('sub_heading_5', models.CharField(default='Sub Heading 5', max_length=500)),
                ('sub_body_5', models.TextField(default='Sub Body 5')),
                ('sub_image_5', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('sub_image_ALT_TAG_5', models.CharField(blank=True, default='Sub Image Default ALT TAG 5', max_length=500, null=True)),
                ('sub_heading_6', models.CharField(default='Sub Heading 6', max_length=500)),
                ('sub_body_6', models.TextField(default='Sub Body 6')),
                ('sub_image_6', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('sub_image_ALT_TAG_6', models.CharField(blank=True, default='Sub Image Default ALT TAG 6', max_length=500, null=True)),
                ('sub_heading_7', models.CharField(blank=True, default='Sub Heading 7', max_length=500, null=True)),
                ('sub_body_7', models.TextField(blank=True, default='Sub Body 7', null=True)),
                ('sub_image_7', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('sub_image_ALT_TAG_7', models.CharField(blank=True, default='Sub Image Default ALT TAG 7', max_length=500, null=True)),
                ('sub_heading_8', models.CharField(blank=True, default='Sub Heading 8', max_length=500, null=True)),
                ('sub_body_8', models.TextField(blank=True, default='Sub Body 8', null=True)),
                ('sub_image_8', models.FileField(blank=True, null=True, upload_to='midea/images/')),
                ('sub_image_ALT_TAG_8', models.CharField(blank=True, default='Sub Image Default ALT TAG 8', max_length=500, null=True)),
            ],
        ),
    ]
