# Generated by Django 4.2 on 2023-04-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0044_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Content',
        ),
    ]
