# Generated by Django 4.2 on 2023-04-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0046_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='blog_date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
