# Generated by Django 4.2 on 2023-04-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0047_alter_blog_content_blog_date_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Content',
        ),
    ]
