# Generated by Django 4.2 on 2023-04-11 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0049_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='blog_date_posted',
            field=models.DateTimeField(default=django.utils.timezone.get_current_timezone_name),
        ),
    ]
