# Generated by Django 4.2 on 2023-04-12 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0053_blog_content_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_content',
            old_name='blog_summary',
            new_name='blog_sub_title',
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='blog_date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
