# Generated by Django 4.2 on 2023-04-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0054_rename_blog_summary_blog_content_blog_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_10',
            field=models.TextField(blank=True, default='Sub Body 8', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_11',
            field=models.TextField(blank=True, default='Sub Body 8', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_12',
            field=models.TextField(blank=True, default='Sub Body 8', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_13',
            field=models.TextField(blank=True, default='Sub Body 8', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_body_9',
            field=models.TextField(blank=True, default='Sub Body 8', null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_10',
            field=models.CharField(blank=True, default='Sub Heading 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_11',
            field=models.CharField(blank=True, default='Sub Heading 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_12',
            field=models.CharField(blank=True, default='Sub Heading 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_13',
            field=models.CharField(blank=True, default='Sub Heading 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_heading_9',
            field=models.CharField(blank=True, default='Sub Heading 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_10',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_11',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_12',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_13',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_9',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_10',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_11',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_12',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_13',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 8', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_9',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 8', max_length=500, null=True),
        ),
    ]
