# Generated by Django 4.2 on 2023-04-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0055_blog_content_sub_body_10_blog_content_sub_body_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='image_info_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_10',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_11',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_12',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_13',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_6',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_7',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_8',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='image_info_9',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_10',
            field=models.TextField(blank=True, default='Sub Body 10', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_11',
            field=models.TextField(blank=True, default='Sub Body 11', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_12',
            field=models.TextField(blank=True, default='Sub Body 12', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_13',
            field=models.TextField(blank=True, default='Sub Body 13', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_body_9',
            field=models.TextField(blank=True, default='Sub Body 9', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_10',
            field=models.CharField(blank=True, default='Sub Heading 10', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_11',
            field=models.CharField(blank=True, default='Sub Heading 11', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_12',
            field=models.CharField(blank=True, default='Sub Heading 12', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_13',
            field=models.CharField(blank=True, default='Sub Heading 13', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_heading_9',
            field=models.CharField(blank=True, default='Sub Heading 9', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_10',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 10', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_11',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 11', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_12',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 12', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_13',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 13', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='sub_image_ALT_TAG_9',
            field=models.CharField(blank=True, default='Sub Image Default ALT TAG 9', max_length=500, null=True),
        ),
    ]
