# Generated by Django 4.2 on 2023-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0058_alter_blog_content_blog_body_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_content',
            name='blog_body_2',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='blog_body_3',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='blog_heading_2',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog_content',
            name='blog_heading_3',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
