# Generated by Django 4.2 on 2023-04-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0059_alter_blog_content_blog_body_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_content',
            name='blog_images_1_ALT_TAG',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='blog_images_2_ALT_TAG',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_content',
            name='blog_images_3_ALT_TAG',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
