# Generated by Django 4.2 on 2023-04-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0060_blog_content_blog_images_1_alt_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_detail',
            old_name='images',
            new_name='images_1',
        ),
        migrations.AddField(
            model_name='product_detail',
            name='images_2',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='images_3',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='images_4',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='images_5',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='images_6',
            field=models.FileField(blank=True, null=True, upload_to='midea/images/'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='product_slug',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
