# Generated by Django 4.2 on 2023-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0061_rename_images_product_detail_images_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='images_2',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='midea/images/'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='images_3',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='midea/images/'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='images_4',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='midea/images/'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='images_5',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='midea/images/'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='images_6',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='midea/images/'),
        ),
    ]
