# Generated by Django 4.2 on 2023-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0065_alter_product_detail_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='product_status',
            field=models.CharField(choices=[('n', None), ('a', 'Available'), ('un', 'UnAvailable')], default='a', max_length=60),
        ),
    ]
