# Generated by Django 4.2 on 2023-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0066_alter_product_detail_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='images_ALT_TAG',
            field=models.CharField(blank=True, default='Image ALT Tag', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='product_status',
            field=models.CharField(choices=[('a', 'Available'), ('un', 'UnAvailable'), ('n', None)], default='a', max_length=60),
        ),
    ]
