# Generated by Django 4.2 on 2023-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0067_testimonials_images_alt_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='product_status',
            field=models.CharField(choices=[('IS', 'In Stock'), ('SO', 'Sold Out'), ('n', None)], default='a', max_length=60),
        ),
    ]
