# Generated by Django 4.2.2 on 2023-06-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0069_alter_product_detail_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_team',
            name='company_name',
            field=models.CharField(default='Apparky', max_length=40),
        ),
    ]
