# Generated by Django 4.2.2 on 2023-06-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0070_out_team_company_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Out_Team',
            new_name='Our_Team',
        ),
    ]
