# Generated by Django 4.2.2 on 2023-06-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0071_rename_out_team_our_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Our_Team',
            new_name='Our_Core_Team',
        ),
    ]
