# Generated by Django 4.2 on 2023-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alt_tag', models.CharField(max_length=300)),
                ('highlights', models.CharField(max_length=150, null=True)),
                ('bg_image', models.ImageField(upload_to='midea/images/')),
            ],
        ),
    ]
