# Generated by Django 4.2 on 2023-04-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background_Image',
        ),
    ]
